POST http://localhost:4000/register
Content-Type: application/json

{
  "firstname": "Tomas",
  "surname": "Jedno",
  "birthdate": "1970-01-01T00:00:00",
  "email": "katka@nova.cz",
  "phonePrefix": "+420",
  "phone": 678456765,
  "insuranceNumber": 456788,
  "country": "Česko",
  "city": "Praha",
  "postalCode": 4589,
  "street": "Dejvická",
  "buildingNumber": "45A",
  "password1": "NOVA",
  "password2": "NOVA"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "katka@nova.cz",
  "password": "NOVA"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "tomas@jedno.com",
  "password": "CUKR"
}

###

PUT http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1Mzg2NDA4MCwiZXhwIjozMzA4MDg4MTYwLCJpc3MiOiJjb29sSXNzdWVyIn0.cqmFFpbjl0G4J-3ijRUrcno9WWVFqZxUKMc1DdLHg5U

###

GET http://localhost:4000/persons

###

GET http://localhost:4000/personal-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYmFuYW4uY29tIiwiaWF0IjoxNjU0NjA5OTM3LCJleHAiOjMzMDk1Nzk4NzQsImlzcyI6ImNvb2xJc3N1ZXIifQ.6TaG7JVwJexX41_pRxMliUOvbf17DnGpqk7L74xvkBs

###

GET http://localhost:4000/person-reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AY2lidWxlLmNvbSIsImlhdCI6MTY1NDUwMzM5MiwiZXhwIjozMzA5MzY2Nzg0LCJpc3MiOiJjb29sSXNzdWVyIn0.HeTamCA3Un7IkYeK-mBJ9POERx-KetMQk5Pis0K7PR8

###

PATCH http://localhost:4000/personal-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYmFuYW4uY29tIiwiaWF0IjoxNjU0NjA3MzgxLCJleHAiOjMzMDk1NzQ3NjIsImlzcyI6ImNvb2xJc3N1ZXIifQ.0mnE68EwYPHEUDGXFfvOwz0TtwvZbDHMfHsQeh8HIiM
Content-Type: application/json

{
  "firstname": "Adam",
  "surname": "Cibule",
  "birthdate": "1970-01-01T00:00:00",
  "email": "adam@banan.com",
  "phonePrefix": "+420",
  "phone": 678456765,
  "insuranceNumber": 456788,
  "country": "Česko",
  "city": "Praha",
  "postalCode": 4589,
  "street": "Dejvická",
  "buildingNumber": "45A",
  "oldPassword": "CUKR",
  "password1": "CUKR",
  "password2": "CUKR"
}

###

PATCH http://localhost:4000/doctor-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYmFuYW4uY29tIiwiaWF0IjoxNjU0NjA3MzgxLCJleHAiOjMzMDk1NzQ3NjIsImlzcyI6ImNvb2xJc3N1ZXIifQ.0mnE68EwYPHEUDGXFfvOwz0TtwvZbDHMfHsQeh8HIiM
Content-Type: application/json

{
  "firstname": "Adam",
  "surname": "Cibule",
  "birthdate": "1970-01-01T00:00:00",
  "email": "adam@banan.com",
  "phonePrefix": "+420",
  "phone": 678456765,
  "insuranceNumber": 456788,
  "country": "Česko",
  "city": "Praha",
  "postalCode": 4589,
  "street": "Dejvická",
  "buildingNumber": "45A",
  "oldPassword": "CUKR",
  "password1": "CIBULE",
  "password1": "CIBULE",
  "specialization": "gynekolog",
  "actuality": "Na dovolené",
  "workCountry": "Česko",
  "workCity": "Praha",
  "workPostalCode": 4589,
  "workStreet": "Dejvická",
  "workBuildingNumber": "45A"
}

###

DELETE http://localhost:4000/personal-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1NDQ5MzM4MiwiZXhwIjozMzA5MzQ2NzY0LCJpc3MiOiJjb29sSXNzdWVyIn0.yzeFajD_eKWWGwsUVBvlMbQIef41rO3YUPQsQ0nuw0Q

###

DELETE http://localhost:4000/doctor-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1NDQ2NTM3MiwiZXhwIjozMzA5MjkwNzQ0LCJpc3MiOiJjb29sSXNzdWVyIn0.I5QPfvyd7fCJ87TkEyl2AWjAul7-9THQfDGO38Sc1Hk

###

GET http://localhost:4000/doctor-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYmFuYW4uY29tIiwiaWF0IjoxNjU0NTI3NzMxLCJleHAiOjMzMDk0MTU0NjIsImlzcyI6ImNvb2xJc3N1ZXIifQ.kox-3vj3bQaBc6NDotaJRytWDM6OvTKClUg6LY3b02E

###

GET http://localhost:4000/doctor-reservation-hours
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGthQG5vdmEuY3oiLCJpYXQiOjE2NTQ3MTA0OTAsImV4cCI6MzMwOTc4MDk4MCwiaXNzIjoiY29vbElzc3VlciJ9.YRzYV4ha9V4ew0ud3biD1xN_GMh0wRnOB0FnGw8SfLE

###

POST http://localhost:4000/doctor-reservation-hours
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGthQG5vdmEuY3oiLCJpYXQiOjE2NTQ3MTAxNTUsImV4cCI6MzMwOTc4MDMxMCwiaXNzIjoiY29vbElzc3VlciJ9.OPAEnSCAWBuy0tynQPzrYdIrizsvNz4OXzQBgRZ3nd8
Content-Type: application/json

{
  "fromDate": "2022-06-08T00:00:00",
  "interval": 30,
  "slots": [
    {
      "fromTime": null,
      "toTime": null
    },
    {
      "fromTime": "9:30",
      "toTime": "10:30"
    },
    {
      "fromTime": "10:00",
      "toTime": "13:00"
    },
    {
      "fromTime": "9:30",
      "toTime": "10:30"
    },
    {
      "fromTime": "9:30",
      "toTime": "10:30"
    },
    {
      "fromTime": "9:30",
      "toTime": "10:30"
    },
     {
      "fromTime": null,
      "toTime": null
    }
  ]
}
###


GET http://localhost:4000/doctors

###

GET http://localhost:4000/doctors-locations

###

GET http://localhost:4000/doctors/1

###
GET http://localhost:4000/doctor-reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbWFzQGplZG5vLmNvbSIsImlhdCI6MTY1NDcwNzg1MiwiZXhwIjozMzA5Nzc1NzA0LCJpc3MiOiJjb29sSXNzdWVyIn0.x0zboMfOnmKDrmT8KOFScTTncajzoZO7TLoevzYjfY8
###
POST http://localhost:4000/doctor/1/reservations-registered
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbWFzQGplZG5vLmNvbSIsImlhdCI6MTY1NDYyNDIxNywiZXhwIjozMzA5NjA4NDM0LCJpc3MiOiJjb29sSXNzdWVyIn0.zIrCMOivsCz4G0sEgLK5uTzHdWgjDVKK0TWlzR7FdTw
Content-Type: application/json

{
  "date": "2022-06-14T00:00:00",
  "time": "10:00",
  "comment": "Operace zubu."
}


###

POST http://localhost:4000/doctor/1/reservations-nonregistered
Content-Type: application/json

{
  "firstname":"Matěj",
  "surname": "Kulhavý",
  "birthdate": "1998-03-05T00:00:00",
  "email": "tomas@jedno.com",
  "phonePrefix": "+420",
  "phone": 666666666,
  "country": "Česko",
  "city": "Brno",
  "postalCode": 56788,
  "street": "Veveří",
  "buildingNumber": "67/B",
  "date": "2022-06-14T00:00:00",
  "time": "10:40",
  "comment": "Operace zubu."
}


###

POST http://localhost:4000/doctors/1/review
Content-Type: application/json

{
  "rate": 5,
  "author": "Já"
}

###

DELETE http://localhost:4000/logout Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

GET http://localhost:4000/doctors/1/slots/2022-06-14

###

GET http://localhost:4000/doctor/:id(\d+)/reservations-registered
Content-Type: application/json


###
