POST http://localhost:4000/register
Content-Type: application/json

{
  "firstname": "Adam",
  "surname": "Cibule",
  "birthdate": "1970-01-01T00:00:00",
  "email": "adam@banan.com",
  "phonePrefix": "+420",
  "phone": 678456765,
  "insuranceNumber": 456788,
  "country": "Česko",
  "city": "Praha",
  "postalCode": 4589,
  "street": "Dejvická",
  "buildingNumber": "45A",
  "password1": "CUKR",
  "password2": "CUKR"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "adam@cibule.com",
  "password": "CUKR"
}

###

PUT http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1Mzg2NDA4MCwiZXhwIjozMzA4MDg4MTYwLCJpc3MiOiJjb29sSXNzdWVyIn0.cqmFFpbjl0G4J-3ijRUrcno9WWVFqZxUKMc1DdLHg5U

###

GET http://localhost:4000/persons

###

GET http://localhost:4000/personal-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1NDQ5MzM4MiwiZXhwIjozMzA5MzQ2NzY0LCJpc3MiOiJjb29sSXNzdWVyIn0.yzeFajD_eKWWGwsUVBvlMbQIef41rO3YUPQsQ0nuw0Q

###

GET http://localhost:4000/person-reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1Mzg2NDA4MCwiZXhwIjozMzA4MDg4MTYwLCJpc3MiOiJjb29sSXNzdWVyIn0.cqmFFpbjl0G4J-3ijRUrcno9WWVFqZxUKMc1DdLHg5U

###

PATCH http://localhost:4000/personal-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1NDQ2NTM3MiwiZXhwIjozMzA5MjkwNzQ0LCJpc3MiOiJjb29sSXNzdWVyIn0.I5QPfvyd7fCJ87TkEyl2AWjAul7-9THQfDGO38Sc1Hk
Content-Type: application/json

{
  "degree": "MUDr.",
}

###

DELETE http://localhost:4000/personal-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1NDQ5MzM4MiwiZXhwIjozMzA5MzQ2NzY0LCJpc3MiOiJjb29sSXNzdWVyIn0.yzeFajD_eKWWGwsUVBvlMbQIef41rO3YUPQsQ0nuw0Q

###

DELETE http://localhost:4000/doctor-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AYW5hbmFzLmNvbSIsImlhdCI6MTY1NDQ2NTM3MiwiZXhwIjozMzA5MjkwNzQ0LCJpc3MiOiJjb29sSXNzdWVyIn0.I5QPfvyd7fCJ87TkEyl2AWjAul7-9THQfDGO38Sc1Hk

###

GET http://localhost:4000/doctors

###

GET http://localhost:4000/doctors-locations

###

GET http://localhost:4000/doctors/1

###
GET http://localhost:4000/doctor-reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AY2lidWxlLmNvbSIsImlhdCI6MTY1NDUwMzM5MiwiZXhwIjozMzA5MzY2Nzg0LCJpc3MiOiJjb29sSXNzdWVyIn0.HeTamCA3Un7IkYeK-mBJ9POERx-KetMQk5Pis0K7PR8

###
POST http://localhost:4000/doctor/1/reservations-registered
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1AY2lidWxlLmNvbSIsImlhdCI6MTY1NDUwMzM5MiwiZXhwIjozMzA5MzY2Nzg0LCJpc3MiOiJjb29sSXNzdWVyIn0.HeTamCA3Un7IkYeK-mBJ9POERx-KetMQk5Pis0K7PR8
Content-Type: application/json

{
  "date": "2022-06-06T00:00:00",
  "interval": 30,
  "slotIndex": 5,
  "comment": "Operace zubu."
}


###

POST http://localhost:4000/doctor/1/reservations-nonregistered
Content-Type: application/json

{
  "firstname":"Matěj",
  "surname": "Kulhavý",
  "birthdate": "1998-03-05T00:00:00",
  "email": "tomas@jedno.com",
  "phonePrefix": "+420",
  "phone": 666666666,
  "country": "Česko",
  "city": "Brno",
  "postalCode": 56788,
  "street": "Veveří",
  "buildingNumber": "67/B",
  "date": "2022-06-06T00:00:00",
  "interval": 30,
  "slotIndex": 5,
  "comment": "Operace zubu."
}


###

DELETE http://localhost:4000/logout Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

GET http://localhost:4000/doctors/1/slots/1970-01-01

###

GET http://localhost:4000/doctor/:id(\d+)/reservations-registered
Content-Type: application/json


###
